spring.application.name=SpringSecurity

# check security config class there i have hardcoded the users instead of doing here
#spring.security.user.name=omhpatil
#spring.security.user.password=omhpatil
#spring.security.user.roles=ADMIN